### ISSUE TITLE
Run demo fail

### ISSUE THREAD

**Issue by s0lut1on** [HMS-Core/hms-wiseplay-demo#1]
I recently run this demo on Emulator device on Deveco studio, matePad pro

And it return fail when I get online license with error message is: fail to open session
![image](https://user-images.githubusercontent.com/56832902/154888817-b211b31e-46fa-40d1-a97c-a1f5913e0b86.png)

Is any note to able to run demo on mobile device ?

**Comment by s0lut1on** [comment]
Seem that Matepad Pro is not suitable device.
When I run demo app on CloudDebugging in AppGallery is don't have fail to open session issue but it return error fail to connect to server
![image](https://user-images.githubusercontent.com/56832902/154890400-e6420e46-74eb-4482-a313-653d493476fc.png)
Is this link is still avaiable: 
[https://wiseplay.hwcloudtest.cn:9091/playdemo/chinaDrm/getLicense?contentId=sfasRAeuyHJFSJA&useDrmProxy=1](url)

**Comment by coolleizhu** [comment]
it is suggested to follow this guide to make debug:

https://developer.huawei.com/consumer/en/doc/development/Media-Guides/wiseplay-resources-0000001057749543

It also needs to add allowlist.

**Comment by s0lut1on** [comment]
Thank for your comment
